services:
  - type: web
    name: portfolio-builder
    env: node
    buildCommand: npm install && cd personal-portfolio-builder-master && npm install && cd client && npm install && npm run build
    startCommand: cd personal-portfolio-builder-master && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: portfolio_builder_secret_key_2024
      - key: MONGODB_URI
        value: mongodb+srv://cys:cys@cluster0.ym6mhyw.mongodb.net/portfolio-builder?retryWrites=true&w=majority&appName=Cluster0